[theme]
base = "dark"
primaryColor = "#60a5fa"              # blue-400 moderado
backgroundColor = "#0b1220"            # slate-950-ish
secondaryBackgroundColor = "#0f172a"   # slate-900 profundo
textColor = "#e2e8f0"                  # slate-200

[browser]
gatherUsageStats = false
